services:
  postgres:
    image: postgres:15-alpine
    container_name: idn_postgres
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - "5432:5432"
    
    volumes:
        - postgres_data:/var/lib/postgresql/data

    networks:
      - idn_network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: idn_redis
    ports:
      - "6379:6379"
    
    volumes:
      - redis_data:/data

    networks:
      - idn_network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  auth-service:
    build: 
      context: ./Auth-service
      dockerfile: Dockerfile
    container_name: idn_auth_service
    ports:
      - "3001:3001"

    environment:
        NODE_ENV: ${NODE_ENV}
        PORT: 3001
        DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
        REDIS_URL: redis://redis:6379
        JWT_SECRET: ${JWT_SECRET}
        JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
        FRONTEND_URL: ${FRONTEND_URL}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - idn_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 3s
      retries: 5
    volumes:
      - ./Auth-service:/app
      - /app/node_modules

    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: idn_frontend
    ports:
      - "3000:3000"
    
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: http://localhost:3001

    depends_on:
      auth-service:
        condition: service_healthy

    networks:
      - idn_network
    
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

    command: npm run dev

networks:
    idn_network:
      driver: bridge

volumes:
    postgres_data:
      driver: local
    redis_data:
      driver: local